// client/src/components/layout/header.tsx
import { Bell, Search, Settings, User } from "lucide-react";
import { Button } from "@/components/ui/button";

export function Header() {
  return (
    <header className="border-b border-border bg-card/50 backdrop-blur supports-[backdrop-filter]:bg-card/50">
      <div className="flex h-16 items-center px-6">
        <div className="flex items-center space-x-3">
          <img 
            src="/logo.png" 
            alt="Merge Sensei Logo" 
            className="h-32 w-32 object-contain"
          />
        </div>
        
        <div className="flex flex-1 items-center justify-center px-6">
          <div className="w-full max-w-sm">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
              <input
                type="search"
                placeholder="Search projects..."
                className="w-full pl-10 pr-4 py-2 bg-background border border-border rounded-lg text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary/20"
                data-testid="input-search-projects"
              />
            </div>
          </div>
        </div>

        <div className="flex items-center space-x-2">
          <Button variant="ghost" size="icon" data-testid="button-notifications">
            <Bell className="h-5 w-5" />
          </Button>
          <Button variant="ghost" size="icon" data-testid="button-settings">
            <Settings className="h-5 w-5" />
          </Button>
          <Button variant="ghost" size="icon" data-testid="button-user-profile">
            <User className="h-5 w-5" />
          </Button>
        </div>
      </div>
    </header>
  );
}

// frontend/admin/src/app/layout/header/header.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Output } from '@angular/core';
import { NgOptimizedImage } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [NgOptimizedImage, FormsModule],
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppHeaderComponent {
  @Output() menuToggle = new EventEmitter<void>();

  search = '';

  onMenuClick(): void {
    this.menuToggle.emit();
  }
}


<header class="app-header border-b backdrop-blur">
  <div class="flex h-16 items-center px-6">
    <button class="md:hidden h-8 w-8 grid place-items-center rounded-md hover:bg-white/5" (click)="onMenuClick()" aria-label="Toggle menu">
      <svg class="w-4 h-4 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 6h18M3 12h18M3 18h18"/></svg>
    </button>

    <div class="relative hidden md:block ml-3 w-80">
      <svg class="pointer-events-none absolute left-3 top-2.5 w-4 h-4 shrink-0 text-gray-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="7"/><path d="M21 21l-4.3-4.3"></path></svg>
      <input class="h-9 w-80 rounded-md border border-white/10 bg-white/5 pl-9 pr-3 text-sm placeholder:text-gray-400 text-gray-100 focus:outline-none focus:ring-2 focus:ring-white/20" placeholder="Search… (Ctrl+K)" [(ngModel)]="search" />
    </div>

    <div class="ml-auto flex items-center gap-1">
      <button class="md:hidden h-8 w-8 grid place-items-center rounded-md hover:bg-white/5" aria-label="Search">
        <svg class="w-4 h-4 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="7"></circle><path d="M21 21l-4.3-4.3"></path></svg>
      </button>
      <button class="h-8 w-8 grid place-items-center rounded-md hover:bg-white/5" aria-label="Notifications">
        <svg class="w-4 h-4 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/></svg>
      </button>
      <button class="h-8 w-8 grid place-items-center rounded-md hover:bg-white/5" aria-label="Settings">
        <svg class="w-4 h-4 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M19.4 12.9l1.4-2.4-1.8-3.1-2.8.4-1.6-2.3h-3.6L8.4 7.8l-2.8-.4-1.8 3.1 1.4 2.4-1.4 2.4 1.8 3.1 2.8-.4 1.6 2.3h3.6l1.6-2.3 2.8.4 1.8-3.1-1.4-2.4z"/></svg>
      </button>

      <button class="ml-1 h-8 w-8 rounded-full hover:bg-white/5 grid place-items-center" aria-label="User menu">
        <img src="assets/logo.png" width="32" height="32" class="w-8 h-8 rounded-full" alt="Avatar" />
      </button>
    </div>
  </div>
</header>
