// frontend/admin/src/app/pages/help/help.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { FormsModule } from '@angular/forms';

interface ChatMessage {
  id: string;
  type: 'bot' | 'user';
  message: string;
  timestamp: Date;
}

interface FaqItem {
  id: string;
  question: string;
  answer: string;
}

@Component({
  selector: 'app-help',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule],
  templateUrl: './help.component.html',
  styleUrls: ['./help.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HelpComponent {
  // TODO: i18n
  activeTab = 'faq';

  chatMessages: ChatMessage[] = [
    {
      id: '1',
      type: 'bot',
      message:
        "Hello! I'm your AI assistant. How can I help you with your pipelines today?",
      timestamp: new Date(),
    },
  ];

  chatInput = '';
  expandedFaq: string | null = null;

  faqItems: FaqItem[] = [
    {
      id: '1',
      question: 'How do I create a new pipeline?',
      answer:
        "Go to a project and click 'Create Pipeline'. Follow the 4-step wizard to configure your pipeline with AI agents and triggers.",
    },
    {
      id: '2',
      question: 'What AI agents are available?',
      answer:
        'We offer several AI agents including Code Review (automated code quality analysis), Security Scanner (vulnerability detection), Performance Analyzer (bottleneck detection), Test Generator (automatic test creation), Documentation AI (auto-documentation), and API Validator (contract validation).',
    },
    {
      id: '3',
      question: 'How do pipeline triggers work?',
      answer:
        'Pipeline triggers determine when your pipeline runs automatically. You can set triggers for push events to specific branches (main, staging, production), pull request creation, scheduled runs (daily/weekly), or manual execution only.',
    },
    {
      id: '4',
      question: 'Can I modify an existing pipeline?',
      answer:
        "Yes, you can edit pipeline settings by going to the project detail page, finding your pipeline in the list, and clicking 'View Details'. From there you can modify the name, enabled agents, and trigger conditions.",
    },
    {
      id: '5',
      question: 'How do I interpret pipeline results?',
      answer:
        "Pipeline results show the status (Active/Inactive), last run time, and detailed reports from each AI agent. Green status indicates successful runs, while red indicates issues that need attention. Click 'View Details' for comprehensive reports.",
    },
  ];

  setActiveTab(tab: string) {
    this.activeTab = tab;
  }

  toggleFaq(id: string) {
    this.expandedFaq = this.expandedFaq === id ? null : id;
  }

  handleSendMessage() {
    if (!this.chatInput.trim()) {
      return;
    }

    const userMessage: ChatMessage = {
      id: Date.now().toString(),
      type: 'user',
      message: this.chatInput,
      timestamp: new Date(),
    };

    this.chatMessages = [...this.chatMessages, userMessage];
    this.chatInput = '';

    setTimeout(() => {
      const botResponse: ChatMessage = {
        id: (Date.now() + 1).toString(),
        type: 'bot',
        message:
          "I understand your question. Let me help you with that. Could you provide more details about what specific aspect you'd like to know more about?",
        timestamp: new Date(),
      };
      this.chatMessages = [...this.chatMessages, botResponse];
    }, 1000);
  }

  onKeyDown(event: KeyboardEvent) {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault();
      this.handleSendMessage();
    }
  }
}

<div class="space-y-6">
  <div>
    <h1 class="text-3xl font-bold title" data-testid="text-help-title">Help &amp; Support</h1>
    <p class="mt-1 subtitle" data-testid="text-help-subtitle">
      Get help and support for your questions
    </p>
  </div>

  <div class="space-y-6">
    <div class="grid w-full grid-cols-2">
      <button
        class="flex items-center justify-center p-2"
        [ngClass]="activeTab === 'faq' ? 'border-b-2 font-semibold' : 'border-b'"
        (click)="setActiveTab('faq')"
        data-testid="tab-faq"
      >
        <svg
          class="w-4 h-4 mr-2"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <path d="m21 21-4.34-4.34" />
          <circle cx="11" cy="11" r="8" />
        </svg>
        FAQ
      </button>
      <button
        class="flex items-center justify-center p-2"
        [ngClass]="activeTab === 'chat' ? 'border-b-2 font-semibold' : 'border-b'"
        (click)="setActiveTab('chat')"
        data-testid="tab-chat"
      >
        <svg
          class="w-4 h-4 mr-2"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <path
            d="M2.992 16.342a2 2 0 0 1 .094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413-.998a2 2 0 0 1 1.099.092 10 10 0 1 0-4.777-4.719"
          />
        </svg>
        AI Assistant
      </button>
    </div>

    @if (activeTab === 'faq') {
      <div class="bg-white rounded-lg shadow-md" data-testid="card-faq">
        <div class="p-6 border-b">
          <h2 class="text-lg font-semibold">Frequently Asked Questions</h2>
        </div>
        <div class="p-6">
          <div class="space-y-4">
            @for (item of faqItems; track item.id) {
              <div class="border rounded-lg" data-testid="faq-item-{{ item.id }}">
                <button
                  class="w-full p-4 text-left flex items-center justify-between hover:bg-gray-100 transition-colors"
                  (click)="toggleFaq(item.id)"
                  data-testid="faq-question-{{ item.id }}"
                >
                  <span class="font-medium">{{ item.question }}</span>
                  @if (expandedFaq === item.id) {
                    <svg
                      class="w-5 h-5 text-gray-500"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      stroke-width="2"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    >
                      <path d="m6 9 6 6 6-6" />
                    </svg>
                  } @else {
                    <svg
                      class="w-5 h-5 text-gray-500"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      stroke-width="2"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    >
                      <path d="m9 18 6-6-6-6" />
                    </svg>
                  }
                </button>
                @if (expandedFaq === item.id) {
                  <div
                    class="p-4 border-t faq-answer"
                    data-testid="faq-answer-{{ item.id }}"
                  >
                    <p class="muted-text">{{ item.answer }}</p>
                  </div>
                }
              </div>
            }
          </div>
        </div>
      </div>
    }

    @if (activeTab === 'chat') {
      <div class="bg-white rounded-lg shadow-md" data-testid="card-ai-chat">
        <div class="p-6 border-b">
          <h2 class="text-lg font-semibold flex items-center">
            <svg
              class="w-5 h-5 mr-2"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <path d="M12 8V4H8" />
              <rect width="16" height="12" x="4" y="8" rx="2" />
              <path d="M2 14h2" />
              <path d="M20 14h2" />
              <path d="M15 13v2" />
              <path d="M9 13v2" />
            </svg>
            AI Assistant
          </h2>
        </div>
        <div class="p-6">
          <div class="space-y-4">
            <div
              class="h-96 border rounded-lg p-4 overflow-y-auto space-y-4"
              data-testid="chat-messages"
            >
              @for (message of chatMessages; track message.id) {
                <div
                  class="flex"
                  [class.justify-end]="message.type === 'user'"
                  [class.justify-start]="message.type === 'bot'"
                  data-testid="chat-message-{{ message.id }}"
                >
                  <div
                    class="max-w-xs lg:max-w-md px-4 py-2 rounded-lg"
                    [ngClass]="message.type === 'user' ? 'user-msg' : 'bot-msg'"
                  >
                    <p class="text-sm">{{ message.message }}</p>
                    <p class="text-xs mt-1 timestamp">
                      {{ message.timestamp | date: 'shortTime' }}
                    </p>
                  </div>
                </div>
              }
            </div>

            <div class="flex space-x-2">
              <textarea
                [(ngModel)]="chatInput"
                placeholder="Ask me anything about pipelines, projects, or platform features..."
                class="flex-1 min-h-[60px] resize-none p-2 rounded-md border"
                (keydown)="onKeyDown($event)"
                data-testid="textarea-chat-input"
              ></textarea>
              <button
                class="px-4 py-2 rounded-md send-btn"
                (click)="handleSendMessage()"
                [disabled]="!chatInput.trim()"
                data-testid="button-send-message"
              >
                <svg
                  class="w-4 h-4"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                >
                  <path
                    d="M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z"
                  />
                  <path d="m21.854 2.147-10.94 10.939" />
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    }
  </div>
</div>

// react-source/client/src/pages/help.tsx
import { useState } from "react";
import { Send, MessageCircle, Search, ChevronDown, ChevronRight, Bot } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { useTranslation } from "@/contexts/language-context";

export function Help() {
  const { t } = useTranslation();
  type ChatMessage = {
    id: string;
    type: "bot" | "user";
    message: string;
    timestamp: Date;
  };

  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([
    {
      id: "1",
      type: "bot",
      message: "Hello! I'm your AI assistant. How can I help you with your pipelines today?",
      timestamp: new Date(),
    }
  ]);
  const [chatInput, setChatInput] = useState("");
  const [expandedFaq, setExpandedFaq] = useState<string | null>(null);

  const faqItems = [
    {
      id: "1",
      question: "How do I create a new pipeline?",
      answer: "To create a new pipeline, navigate to your project page and click the 'Configure Pipeline' button. This will open a step-by-step wizard that guides you through naming your pipeline, selecting AI agents, and setting trigger conditions."
    },
    {
      id: "2",
      question: "What AI agents are available?",
      answer: "We offer several AI agents including Code Review (automated code quality analysis), Security Scanner (vulnerability detection), Performance Analyzer (bottleneck detection), Test Generator (automatic test creation), Documentation AI (auto-documentation), and API Validator (contract validation)."
    },
    {
      id: "3",
      question: "How do pipeline triggers work?",
      answer: "Pipeline triggers determine when your pipeline runs automatically. You can set triggers for push events to specific branches (main, staging, production), pull request creation, scheduled runs (daily/weekly), or manual execution only."
    },
    {
      id: "4",
      question: "Can I modify an existing pipeline?",
      answer: "Yes, you can edit pipeline settings by going to the project detail page, finding your pipeline in the list, and clicking 'View Details'. From there you can modify the name, enabled agents, and trigger conditions."
    },
    {
      id: "5",
      question: "How do I interpret pipeline results?",
      answer: "Pipeline results show the status (Active/Inactive), last run time, and detailed reports from each AI agent. Green status indicates successful runs, while red indicates issues that need attention. Click 'View Details' for comprehensive reports."
    },
  ];

  const handleSendMessage = () => {
    if (!chatInput.trim()) return;

    const userMessage: ChatMessage = {
      id: Date.now().toString(),
      type: "user",
      message: chatInput,
      timestamp: new Date(),
    };

    setChatMessages(prev => [...prev, userMessage]);
    setChatInput("");

    // Simulate AI response
    setTimeout(() => {
      const botResponse: ChatMessage = {
        id: (Date.now() + 1).toString(),
        type: "bot",
        message: "I understand your question. Let me help you with that. Could you provide more details about what specific aspect you'd like to know more about?",
        timestamp: new Date(),
      };
      setChatMessages(prev => [...prev, botResponse]);
    }, 1000);
  };

  const toggleFaq = (id: string) => {
    setExpandedFaq(expandedFaq === id ? null : id);
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold text-foreground" data-testid="text-help-title">
          {t('help.title')}
        </h1>
        <p className="text-muted-foreground mt-1" data-testid="text-help-subtitle">
          {t('help.subtitle')}
        </p>
      </div>

      <Tabs defaultValue="faq" className="space-y-6">
        <TabsList className="grid w-full grid-cols-2">
          <TabsTrigger value="faq" data-testid="tab-faq">
            <Search className="w-4 h-4 mr-2" />
            {t('help.faq')}
          </TabsTrigger>
          <TabsTrigger value="chat" data-testid="tab-chat">
            <MessageCircle className="w-4 h-4 mr-2" />
            {t('help.aiAssistant')}
          </TabsTrigger>
        </TabsList>

        <TabsContent value="faq" className="space-y-6">
          <Card data-testid="card-faq">
            <CardHeader>
              <CardTitle>Frequently Asked Questions</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {faqItems.map((item) => (
                  <div
                    key={item.id}
                    className="border border-border rounded-lg"
                    data-testid={`faq-item-${item.id}`}
                  >
                    <button
                      className="w-full p-4 text-left flex items-center justify-between hover:bg-muted/50 transition-colors"
                      onClick={() => toggleFaq(item.id)}
                      data-testid={`faq-question-${item.id}`}
                    >
                      <span className="font-medium">{item.question}</span>
                      {expandedFaq === item.id ? (
                        <ChevronDown className="w-5 h-5 text-muted-foreground" />
                      ) : (
                        <ChevronRight className="w-5 h-5 text-muted-foreground" />
                      )}
                    </button>
                    {expandedFaq === item.id && (
                      <div 
                        className="p-4 border-t border-border bg-muted/20"
                        data-testid={`faq-answer-${item.id}`}
                      >
                        <p className="text-muted-foreground">{item.answer}</p>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="chat" className="space-y-6">
          <Card data-testid="card-ai-chat">
            <CardHeader>
              <CardTitle className="flex items-center">
                <Bot className="w-5 h-5 mr-2" />
                AI Assistant
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div 
                  className="h-96 border border-border rounded-lg p-4 overflow-y-auto space-y-4"
                  data-testid="chat-messages"
                >
                  {chatMessages.map((message) => (
                    <div
                      key={message.id}
                      className={`flex ${message.type === 'user' ? 'justify-end' : 'justify-start'}`}
                      data-testid={`chat-message-${message.id}`}
                    >
                      <div
                        className={`max-w-xs lg:max-w-md px-4 py-2 rounded-lg ${
                          message.type === 'user'
                            ? 'bg-primary text-primary-foreground'
                            : 'bg-muted text-muted-foreground'
                        }`}
                      >
                        <p className="text-sm">{message.message}</p>
                        <p className={`text-xs mt-1 ${
                          message.type === 'user' ? 'text-primary-foreground/70' : 'text-muted-foreground/70'
                        }`}>
                          {message.timestamp.toLocaleTimeString()}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
                
                <div className="flex space-x-2">
                  <Textarea
                    value={chatInput}
                    onChange={(e) => setChatInput(e.target.value)}
                    placeholder="Ask me anything about pipelines..."
                    className="min-h-[60px] resize-none"
                    onKeyDown={(e) => {
                      if (e.key === 'Enter' && !e.shiftKey) {
                        e.preventDefault();
                        handleSendMessage();
                      }
                    }}
                    data-testid="textarea-chat-input"
                  />
                  <Button 
                    onClick={handleSendMessage}
                    disabled={!chatInput.trim()}
                    data-testid="button-send-message"
                  >
                    <Send className="w-4 h-4" />
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
